### ISSUE TITLE
1.4 - M1: Milestone 1 Report

### ISSUE THREAD

**Issue by EllynnTeo** [ICT2101-P3Team2/ICT2101_P3-2#4]
- [x] Requirements Specifications
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/9
- [x] Use Case diagram and descriptions
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/11
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/12
- [x] Design Wireframe/ Interfaces
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/5
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/13
- [x] Project Planning & Estimation
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/2
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/3
- https://github.com/ICT2101-P3Team2/ICT2101_P3-2/issues/1
- [x] Individual reflection

https://docs.google.com/document/d/1RWeP1n0OBJM3Nqx0kK2BUYMEDAf4dyq7RVlgEMfTnw0/edit?usp=sharing

**Comment by chococtea** [comment]
Submitted on xSite on 24 Sept 22
